import React, { useState, useEffect } from 'react';
import { RefreshCw, Sparkles, Loader2, BookOpen, Network, Layers } from 'lucide-react';
import { cortexGet, cortexPost } from '@/utils/cortexApi';
import showToast from '@/utils/toast';

export default function CommunitySummaries() {
    const [communities, setCommunities] = useState<any[]>([]);
    const [loading, setLoading] = useState(false);
    const [regenerating, setRegenerating] = useState<string | null>(null);

    // Layer state
    const [layerId, setLayerId] = useState('system_core');
    const [layers, setLayers] = useState<any[]>([]);

    useEffect(() => {
        const fetchLayers = async () => {
            try {
                const data = await cortexGet<any[]>('/api/v1/ops/layers');
                if (data && Array.isArray(data)) {
                    setLayers(data);
                }
            } catch (e) {
                console.error("Failed to fetch layers", e);
            }
        };
        fetchLayers();
    }, []);

    const fetchCommunities = async () => {
        setLoading(true);
        try {
            // Pass layerId as workspace_id param
            const res = await cortexGet<any>(`/api/v1/ops/graph/communities?workspace_id=${layerId}`);
            if (res && res.communities && Array.isArray(res.communities)) {
                setCommunities(res.communities);
            } else {
                setCommunities([]);
            }
        } catch (e) {
            console.error(e);
            setCommunities([]);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchCommunities();
    }, [layerId]);

    const handleRegenerate = async (id: string) => {
        setRegenerating(id);
        try {
            await cortexPost(`/api/v1/ops/graph/communities/${id}/regenerate`, { workspace_id: layerId });
            showToast('Summary regenerated', 'success');
        } catch (e) {
            showToast('Failed to regenerate', 'error');
        } finally {
            setRegenerating(null);
        }
    };

    return (
        <div className="p-4 space-y-6">
            <div className="flex justify-between items-center">
                <div>
                    <h3 className="text-sm font-semibold text-[var(--ink-heading)]">Community Summaries</h3>
                    <p className="text-sm text-[var(--ink-meta)]">
                        Review algorithmic summaries of knowledge clusters generated by Leiden detection.
                    </p>
                </div>
                <div className="flex gap-2 items-center">
                    <select
                        value={layerId}
                        onChange={(e) => setLayerId(e.target.value)}
                        className="px-3 py-1.5 text-sm rounded-lg border border-[var(--ink-border)] bg-white text-[var(--ink-body)] focus:outline-none focus:ring-2 focus:ring-violet-500/20"
                    >
                        {layers.map((layer) => (
                            <option key={layer.id} value={layer.id}>
                                {layer.name} ({layer.type})
                            </option>
                        ))}
                    </select>

                    <button
                        onClick={fetchCommunities}
                        disabled={loading}
                        className="p-2 text-[var(--ink-meta)] hover:text-[var(--ink-heading)] hover:bg-[var(--ink-border)]/50 rounded-lg transition-colors"
                    >
                        <RefreshCw size={16} className={loading ? 'animate-spin' : ''} />
                    </button>
                </div>
            </div>

            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-1">
                {loading ? (
                    <div className="py-12 flex justify-center w-full">
                        <Loader2 size={24} className="animate-spin text-[var(--ink-meta)]" />
                    </div>
                ) : communities.length === 0 ? (
                    <div className="py-12 flex flex-col items-center justify-center text-center p-8 bg-[var(--ink-panel)]/30 border border-dashed border-[var(--ink-border)] rounded-xl">
                        <div className="p-3 bg-[var(--ink-panel)] rounded-full mb-4">
                            <Network size={24} className="text-[var(--ink-muted)]" />
                        </div>
                        <h4 className="text-sm font-bold text-[var(--ink-heading)] mb-2">No Communities Found</h4>
                        <p className="text-sm text-[var(--ink-meta)] max-w-sm">
                            No community summaries found for this layer.
                        </p>
                    </div>
                ) : (
                    communities.map((comm) => (
                        <div key={comm.id} className="bg-white border border-[var(--ink-border)] rounded-xl p-5 hover:border-violet-200 transition-colors group">
                            <div className="flex justify-between items-start mb-3">
                                <div className="flex items-center gap-3">
                                    <div className="p-2 bg-violet-100 text-violet-600 rounded-lg">
                                        <BookOpen size={18} />
                                    </div>
                                    <div>
                                        <h4 className="text-sm font-bold text-[var(--ink-heading)]">{comm.name}</h4>
                                        <p className="text-xs text-[var(--ink-meta)]">{comm.entity_count} entities {comm.last_updated ? `• Updated ${new Date(comm.last_updated).toLocaleDateString()}` : ''}</p>
                                    </div>
                                </div>
                                <button
                                    onClick={() => handleRegenerate(comm.id)}
                                    disabled={!!regenerating}
                                    className="p-2 text-[var(--ink-meta)] hover:text-violet-600 hover:bg-violet-50 rounded-lg transition-colors opacity-0 group-hover:opacity-100"
                                    title="Regenerate Summary"
                                >
                                    {regenerating === comm.id ? <Loader2 size={16} className="animate-spin" /> : <Sparkles size={16} />}
                                </button>
                            </div>

                            <p className="text-sm text-[var(--ink-body)] leading-relaxed bg-[var(--ink-page)]/50 p-3 rounded-lg border border-transparent group-hover:bg-white group-hover:border-[var(--ink-border)] transition-all">
                                {comm.summary}
                            </p>
                        </div>
                    ))
                )}
            </div>
        </div>
    );
}
